version: "3.9"
services:
    console:
        build: .
        ports:
            - "8084:8090"
        depends_on:
            - db
        environment:
            MY: "HelloEnv"

    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            MSSQL_PID: "Express"
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
        ports:
            - "1434:1433"
