version: "3.9"
services:
  application:
    image: "workplacexorg/application-doc"
    ports:
        - "80:80"
    depends_on:
        - db
    environment:
        MY: "HelloEnv"
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      MSSQL_PID: "Express"
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    deploy:
      resources:
        limits:
          memory: 4g
          cpus: '2'
        reservations:
          memory: 4g
          cpus: '2'
    ports:
      - "1433:1433"
